# Generated by Django 5.2.3 on 2025-06-24 12:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.user_image_directory_path, validators=[accounts.models.validate_image_file_size]),
        ),
    ]
