# Generated by Django 5.2.3 on 2025-06-12 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the subscription plan (e.g., 'Gold', 'VIP Sugar Daddy').", max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the plan in NGN (e.g., 5000.00).', max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Duration of the plan in days (e.g., 30 for 1 month, 365 for 1 year).')),
                ('description', models.TextField(blank=True, help_text='Detailed description of plan benefits.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan currently available for purchase?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates if the user has a premium subscription.'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid.', max_digits=10)),
                ('reference', models.CharField(help_text='Unique transaction reference from the payment gateway (e.g., Paystack reference).', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', help_text='Current status of the transaction.', max_length=20)),
                ('gateway_response', models.TextField(blank=True, help_text='Full response received from the payment gateway.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who made the payment.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='The plan associated with this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='When the subscription started.')),
                ('end_date', models.DateTimeField(help_text='When the subscription will expire.')),
                ('is_active', models.BooleanField(default=True, help_text='Is the subscription currently active?')),
                ('plan', models.ForeignKey(help_text='The subscription plan purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='accounts.subscriptionplan')),
                ('user', models.OneToOneField(help_text='The user who holds this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
