# Generated by Django 5.2.3 on 2025-06-26 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_type_userprofile_looking_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR_DADDY', 'Sugar Daddy'), ('SUGAR_MUMMY', 'Sugar Mummy'), ('SEXCALL', 'Sexcall')], default='DATING', help_text='What type of connection are you looking for (dating, hookup, sugar daddy/mummy, sexcall)?', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='+00000000000', help_text='Your WhatsApp phone number including country code (e.g., +2348012345678)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seeking',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('A', 'Anyone')], help_text='Who are you seeking (gender preference)?', max_length=1, null=True),
        ),
    ]
