# Generated by Django 5.2.3 on 2025-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_looking_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR_DADDY', 'Sugar Daddy'), ('SUGAR_MUMMY', 'Sugar Mummy'), ('SEXCALL', 'Sex Call')], default='DATING', help_text='Are you looking for dating, hookups, or are you a sugar daddy/mummy?', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your WhatsApp phone number including country code (e.g., +2348012345678)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seeking',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('A', 'Anyone')], help_text='Who are you seeking?', max_length=1, null=True),
        ),
    ]
