# Generated by Django 5.2.3 on 2025-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of features included in this plan (e.g., ['Ad-free experience', 'Send unlimited messages'])"),
        ),
    ]
