"""
Django settings for loveny_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url # For connecting to various databases (e.g., PostgreSQL)
import dotenv # For loading environment variables from .env file

# Load environment variables from .env file.
# This should be at the very top of the settings file.
dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load SECRET_KEY from environment variable for production.
# Provide a fallback for local development only.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-k%x5v6&x!j1a0m@+&k(m&z)r8v$4s#a8a-0@k%m3r@3y3z0g3v')

# SECURITY WARNING: don't run with debug turned on in production!
# Load DEBUG from environment variable. It should be 'False' in production.
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# ALLOWED_HOSTS for your production server (e.g., your domain name)
# Load from environment variable, split by comma.
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts', # Your custom accounts app
    'widget_tweaks', # For styling forms in templates
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loveny_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Project-level templates directory
        'APP_DIRS': True, # This allows Django to find templates in app_name/templates/app_name/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loveny_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/topics/databases/
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600 # Optional: Reconnect after 10 minutes to prevent stale connections
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/topics/auth/passwords/

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.UserProfile'


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos' # Keeping this as it's a general setting, not deployment-specific

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/topics/files/static-files/

STATIC_URL = 'static/'
# This is where Django will look for additional static files
# beyond what's in app-specific static folders during development.
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Your project-level static directory
]
# The absolute path to the directory where `python manage.py collectstatic` will gather all static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # This will be C:\Users\yanex\Documents\LOVENY_App\media


# Default profile picture path for users without one.
# This should be a path relative to STATIC_URL.
DEFAULT_PROFILE_PICTURE_PATH = 'default_avatar.png' # Assuming it's directly under your /static/ folder

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Redirect URLs after login/logout
LOGIN_REDIRECT_URL = 'accounts:profile_edit'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Paystack Settings
# Load Paystack API keys from environment variables
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
